definitions:
 env_versions: &env_versions
   xcode: 13.3
 triggering:
  push: &push_event
      events:
        - push
 scripts:
    - &install
      name: Installing
      script: |
          pod install
          gem install rake && bundle install
    - &test 
      name: Run tests 
      script: | 
          arch -arm64 xcode-project run-tests \
          --workspace UpcomingMovies.xcworkspace \
          --scheme UpcomingMovies \
          --device "iPhone 11"
    - &build
      name: Run build 
      script: xcodebuild build -workspace "UpcomingMovies.xcworkspace" -scheme "UpcomingMovies" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.4' -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
workflows:
  ios-mac-pro-workflow:
    name: Mac Pro Workflow
    instance_type: mac_pro
    environment:
      <<: *env_versions
    triggering: 
      <<: *push_event
    scripts:
      - *install
      - *build
      - *test
  ios-m1-rosetta-workflow:
    name: M1 Rosetta Workflow
    instance_type: mac_mini_m1
    environment:
      <<: *env_versions
    triggering: 
      <<: *push_event
    scripts:
      - *install
      - uname -m
      - *build
      - *test
